language: cpp
matrix:
  include:
    # Tests on Ubuntu 14.04
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - fakeroot
            - devscripts
            - debhelper
            - build-essential
            - cmake
            - libwxgtk3.0-dev
    # Tests on Ubuntu 16.04
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - fakeroot
            - devscripts
            - debhelper
            - build-essential
            - cmake
            - libwxgtk3.0-dev
    # Tests on Ubuntu 18.04
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - fakeroot
            - devscripts
            - debhelper
            - build-essential
            - cmake
            - libwxgtk3.0-gtk3-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - make
  - sudo make install
  - sudo debuild -us -uc
